### ISSUE TITLE
Missing Close Button [x] in Purchasely UI After Upgrade to Version 4.4.0

### ISSUE THREAD

**Issue by lokile** [Purchasely/Purchasely-Android#10]
Hi Purchasely support team,

After updating to version `4.4.0` in `Android`, we noticed that the close button is missing in the Purchasely UI

**Comment by kherembourg** [comment]
Hello @lokile 
From my tests, everything seems fine with this new release

Can you contact the support email or support on intercom (blue bubble at the bottom right of the console) please?
We would be able to look into your account and check directly your paywall

Thank you
